runtime: python311
service: default

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  EMAIL_ADDRESS: "mayez.ghouma@etudiant-fst.utm.tn"
  EMAIL_PASSWORD: "esitgitlztgwwfrk"
  CSV_FILE_PATH: "data/contacts_real.csv"
  CV_FILE_PATH: "assets/cv_Mayez-Ghouma.pdf"
  START_HOUR: "0"
  END_HOUR: "23"
  TEST_MODE: "true"