runtime: python311
service: default

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  EMAIL_ADDRESS: "akrem.alamine@gmail.com"
  EMAIL_PASSWORD: "apkrvuqqrhhwscas"
  CSV_FILE_PATH: "data/contacts_real.csv"
  CV_FILE_PATH: "assets/Akrem_Alamine_ENOP.pdf"
  START_HOUR: "9"
  END_HOUR: "17"
  START_HOUR: "9"
  END_HOUR: "17"